#We want this to be a C++ file since our complex types require C++.

File.open("lapacke.cpp","w") do |file|
  file.puts "//This file is auto-generated by make_lapacke_cpp.rb"
  file.puts "//It includes all source files in the lapacke/ subdirectory"
  Dir["lapacke/**/*.c"].each do |file2|
    file.puts "#include \"#{file2}\""
  end
end
